server:
  port: 8085
spring:
  devtools:
    add-properties: true
  datasource:
    url: "jdbc:mysql://dev-database.cwfjsyuf7mwr.ap-northeast-2.rds.amazonaws.com:3306/fivekim"
    username: admin
    password: admin123
  jpa:
    hibernate:
      ddl-auto: 'none'
    show-sql: true
    properties:
      format_sql: true
      use_sql_comments: true
  # google email sender
  mail:
    host: smtp.gmail.com
    port: 587
    username: kwx4957@gmail.com
    password: xvrxhtsmjfsneiku
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  data:
    redis:
      host: redis-18164.c290.ap-northeast-1-2.ec2.cloud.redislabs.com
      port: 18164
      password: thZlGuE3PH1pQ5aJaJRGVUzrez4NVBdD
# aws configure
cloud:
  aws:
    credentials:
      access-key: AKIA4HDFBECQIMP3D5XD
      secret-key: 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
    region:
      static: ap-northeast-2
    stack:
      auto: false

# jwt secret key
jwt:
  secret-key: 4D635166546A576E5A7234753778214125442A472D4B614E645267556B587032
  access-token-exp: 360000
  refresh-token-exp: 2592000